<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE matd [
<!ELEMENT matd (title, intro, copyright, class+)>
<!ELEMENT class (group-specimen, designer+, thanks)>
<!ELEMENT year   (#PCDATA)>
<!ELEMENT group-specimen   (specimen, size)>
<!ELEMENT designer  (name, country, email, web, typeface, preview, specimen, webspecimen, rop)>
<!ELEMENT name   (#PCDATA)>
<!ELEMENT country   (#PCDATA)>
<!ELEMENT email  (#PCDATA)>
<!ELEMENT web  (#PCDATA)>
<!ELEMENT typeface  (#PCDATA)>
<!ELEMENT preview  (#PCDATA)>
<!ELEMENT specimen  (#PCDATA)>
<!ELEMENT rop  (#PCDATA)>
<!ELEMENT thanks  (p+)>
<!ELEMENT p  (#PCDATA)>
]>

<matd>
	
<title>MA Typeface Design at the University of Reading</title>

<intro>
Download PDF specimens of the typefaces, Reflection on Practice essays on the development of the typefaces, and contact the designers.
Read more about the course at the <a href="http://www.reading.ac.uk/typography/">Department of Typography
and Graphic Communication</a> website.	
</intro>

<copyright>
Typeface designs © the respective authors, 2000–2010.<br />
Website design and production © <a href="http://davi.cz">David Březina</a>, 2007–2010.<br />
The typeface used in the headline is Ronnia by <a href="http://www.type-together.com/Ronnia">TypeTogether</a>.<br />
Last update: 7 September 2010 — <a href="http://feeds.feedburner.com/matd/">RSS feed</a>
</copyright>

<!-- EMPTY YEAR TEMPLATE -->
<!-- Notes: if you do not want to include specimen, webspecimen, web, rop, vendor, email, just do not include the tag or comment it out. Everything else is obligatory. See previous years for examples of how to fill in the data. Do not use http:// in urls. Include either specimen (name of the PDF on FTP server) or webspecimen (that is link to a website) or none not both at the same time. Preferably specimen of course.
-->

<!--
<class year="2009" ready="0">
	<group-specimen>
		<specimen>matd10_group_specimen.pdf</specimen>
		<size>1.4 MB</size>
	</group-specimen>

    <designer>
		<name></name>
		<country></country>
		<email></email>
		<web></web>
		<typeface></typeface>
		<preview></preview>
		<specimen></specimen>
		<rop></rop>
	</designer>
	
	<thanks>
	<p>We are all very grateful to a lot of people who helped to make this extraordinary year possible.</p>
	<p>We would like to thank the tutors and staff of the Department of Typography &amp; Graphic Communication, University of Reading, especially Martin Andrews, Gerry Leonidas, James Mosley, Fiona Ross, Michael Twyman, and Gerard Unger.</p>
	<p>We couldn’t have done it without all our families and friends, either!</p>
	</thanks>

</class>
-->

<class year="2011" ready="1">
	<group-specimen>
		<specimen>matd11_group_specimen.pdf</specimen>
		<size>1.7 MB</size>
	</group-specimen>

    <designer>
		<name>Pria Adireddi</name>
		<country>India</country>
		<email>pria.adireddi@gmail.com</email>
		<!-- <web></web> -->
		<typeface>the Herald</typeface>
		<preview>PriaAdireddi_theHerald.png</preview>
		<specimen>PriaAdireddi_theHerald_specimen.pdf</specimen>
		<rop>PriaAdireddi_theHerald_ROP.pdf</rop>
	</designer>

    <designer>
		<name>Luisa Baeta</name>
		<country>Brazil / Portugal</country>
		<email>luisabaeta@gmail.com</email>
		<web>www.luisabaeta.com</web>
		<typeface>Arlecchino</typeface>
		<preview>LuisaBaeta_Arlecchino.png</preview>
		<specimen>LuisaBaeta_Arlecchino_specimen.pdf</specimen>
		<rop>LuisaBaeta_Arlecchino_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Aaron Bell</name>
		<country>USA</country>
		<email>hi@aaronb.net</email>
		<web>aaronb.net</web>
		<typeface>Saja</typeface>
		<preview>aaronbell_saja.png</preview>
		<specimen>AaronBell_Saja_specimen.pdf</specimen>
		<rop>AaronBell_Saja_ROP.pdf</rop>
	</designer>

    <designer>
		<name>Bianca Berning</name>
		<country>Germany</country>
		<email>clint@biancaberning.co.uk</email>
		<web>biancaberning.co.uk</web>
		<typeface>Clint</typeface>
		<preview>BiancaBerning_Clint.png</preview>
		<specimen>BiancaBerning_Clint_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

    <designer>
		<name>Eleni Beveratou</name>
		<country>Greece</country>
		<email>eleni@beveratos.com</email>
		<web>www.elenibeveratou.com</web>
		<typeface>Intone</typeface>
		<preview>EleniBeveratou_intone.png</preview>
		<specimen>EleniBeveratou_Intone_specimen.pdf</specimen>
		<rop>EleniBeveratou_Intone_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Marion Delsuc</name>
		<country>France</country>
		<email>marion.delsuc@gmail.com</email>
		<!-- 		<web></web> -->
		<typeface>Cassiope</typeface>
		<preview>MarionDelsuc_Cassiope.png</preview>
		<specimen>MarionDelsuc_Cassiope_specimen.pdf</specimen>
		<rop>MarionDelsuc_Cassiope_ROP.pdf</rop>
	</designer>

    <designer>
		<name>Hanna Donker</name>
		<country>Netherlands</country>
		<email>info@hannadonker.nl</email>
		<web>www.hannadonker.nl</web>
		<typeface>Foxhill</typeface>
		<preview>HannaDonker_Foxhill.png</preview>
		<specimen>HannaDonker_Foxhill_specimen.pdf</specimen>
		<rop>HannaDonker_Foxhill_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Ben Jones</name>
		<country>United Kingdom</country>
		<email>benjones@protimient.com</email>
		<web>www.protimient.com</web>
		<typeface>Emrys</typeface>
		<preview>BenJones_Emrys.png</preview>
		<specimen>BenJones_Emrys_specimen.pdf</specimen>
		<rop>BenJones_Emrys_RoP.pdf</rop>
	</designer>
	
    <designer>
		<name>Rob McKaughan</name>
		<country>USA</country>
		<email>matd@robmck.com</email>
		<web>robmck.com</web>
		<typeface>Chepman</typeface>
		<preview>RobMcKaughan_Chepman.png</preview>
		<specimen>RobMcKaughan_Chepman_specimen.pdf</specimen>
		<rop>RobMcKaughan_Chepman_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Ferran Milan</name>
		<country>Catalonia, Spain</country>
		<email>polytonic3@gmail.com</email>
		<!-- 	<web></web> -->
		<typeface>Bubblegum</typeface>
		<preview>FerranMilan_Bubblegum.png</preview>
		<specimen>FerranMilan _Bubblegum_Specimen.pdf</specimen>
		<rop>FerranMilan_Bubblegum_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Julián Moncada</name>
		<country>Colombia</country>
		<email>jmoncada86@yahoo.com</email>
		<!-- 		<web></web> -->
		<typeface>Lemona</typeface>
		<preview>JulianMoncada_Lemona.png</preview>
		<specimen>JulianMoncada_Lemona_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

    <designer>
		<name>Toshi Omagari</name>
		<country>Japan</country>
		<email>tosche@mac.com</email>
		<!-- 		<web></web> -->
		<typeface>Marco</typeface>
		<preview>ToshiOmagari_Marco.png</preview>
		<specimen>ToshiOmagari_Marco_Specimen.pdf</specimen>
		<rop>Toshi_Omagari_Marco_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Blondina Elms Pastel</name>
		<country>Barbados</country>
		<email>blondina@atelierelms.com</email>
		<web>www.atelierelms.com</web>
		<typeface>Naej</typeface>
		<preview>BlondinaElmsPastel_Naej.png</preview>
		<specimen>BlondinaElmsPastel_Naej_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

    <designer>
		<name>Elena Schneider</name>
		<country>Germany</country>
		<email>hello@elefont.de</email>
		<web>www.elefont.de</web>
		<typeface>Eskorte</typeface>
		<preview>ElenaSchneider_Eskorte.png</preview>
		<specimen>ElenaSchneider_Eskorte_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

    <designer>
		<name>Joana Correia da Silva</name>
		<country>Portugal</country>
		<email>joanamcsilva@gmail.com</email>
		<web>www.joanamcorreia.com</web>
		<typeface>Artigo</typeface>
		<preview>JoanaCorreia_Artigo.png</preview>
		<specimen>JoanaCorreia_Artigo_specimen.pdf</specimen>
		<rop>JoanaSilva_Artigo_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Vaibhav Singh</name>
		<country>India</country>
		<email>errorsinc@gmail.com</email>
		<!-- 		<web></web> -->
		<typeface>Eczar</typeface>
		<preview>VaibhavSingh_Eczar.png</preview>
		<specimen>VaibhavSingh_Eczar_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

    <designer>
		<name>Adrien Vasquez</name>
		<country>France</country>
		<email>blackhole@adrienvasquez.co.uk</email>
		<web>www.adrienvasquez.co.uk</web>
		<typeface>Modern 7</typeface>
		<preview>AdrienVasquez_Modern7.png</preview>
		<specimen>AdrienVasquez_Modern7_specimen.pdf</specimen>
<!-- 
		<rop></rop>
 -->
	</designer>

	<thanks>
	<p>We are all very grateful to a lot of people who helped to make this extraordinary year possible.</p>
	<p>We would like to thank the tutors and staff of the Department of Typography &amp; Graphic Communication, University of Reading, especially Martin Andrews, Gerry Leonidas, James Mosley, Fiona Ross, Michael Twyman, and Gerard Unger.</p>
	<p>We couldn’t have done it without all our families and friends, either!</p>
	</thanks>

</class>


<class year="2010" ready="1">
	<!-- <group-specimen>
		<specimen>matd10_group_specimen.pdf</specimen>
		<size>1.4 MB</size>
	</group-specimen> -->

    <designer>
		<name>Nicole Fally</name>
		<country>Austria/Germany</country>
		<email>nf@t-g-d.at</email>
		<web>www.t-g-d.at</web>
		<typeface>Miss Informed</typeface>
		<preview>NicoleFally_MissInformed.png</preview>
		<specimen>NicoleFally_MissInformed_specimen.pdf</specimen>
		<rop>NicoleFally_MissInformed_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Riccardo De Franceschi</name>
		<country>Italy</country>
		<email>defranceschi@mail.com</email>
		<web>www.rdftype.it/</web>
		<typeface>Ginnasio</typeface>
		<preview>RiccardoDeFranceschi_Ginnasio.png</preview>
		<specimen>RiccardoDeFranceschi_Ginnasio_specimen.pdf</specimen>
		<rop>RiccardoDeFranceschi_Ginnasio_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Mary Louise Killen</name>
		<country>USA</country>
		<email>marylouisekillen@gmail.com</email>
		<web>www.marylouisekillen.com</web>
		<typeface>Acadie &amp; Yala</typeface>
		<preview>MaryLouiseKillen_AcadieYala.png</preview>
		<specimen>MaryLouiseKillen_AcadieYala_specimen.pdf</specimen>
		<rop>MaryLouiseKillen_AcadieYala_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Neelakash Kshetrimayum</name>
		<country>India</country>
		<email>neelakash.k@gmail.com</email>
		<web>www.neelakash.com</web>
		<typeface>Frijky</typeface>
		<preview>NeelakashKshetrimayum_Frijky.png</preview>
		<specimen>NeelakashKshetrimayum_Frijky_specimen.pdf</specimen>
		<!-- <rop>NeelakashKshetrimayum_Frijky_RoP.pdf</rop> !! no share at the moment -->
	</designer>

    <designer>
		<name>Karolina Lach</name>
		<country>Poland/USA</country>
		<email>karolina.lach@gmail.com</email>
		<web>www.thekarolina.com</web>
		<typeface>Sora</typeface>
		<preview>KarolinaLach_Sora.png</preview>
		<specimen>KarolinaLach_Sora_specimen.pdf</specimen>
		<!-- <rop>KarolinaLach_Sora_RoP.pdf</rop> !! no share at the moment -->
	</designer>
	
	<designer>
		<name>Erin McLaughlin</name>
		<country>USA</country>
		<email>hello@erinmclaughlin.com</email>
		<web>www.erinmclaughlin.com</web>
		<typeface>Katari</typeface>
		<preview>ErinMcLaughlin_Katari.png</preview>
		<specimen>ErinMcLaughlin_Katari_specimen.pdf</specimen>
		<rop>ErinMcLaughlin_Katari_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Marian Misiak</name>
		<country>Poland/Czechia</country>
		<email>jaduone@o2.pl</email>
		<web>www.berszmisiak.com</web>
		<typeface>Timeline</typeface>
		<preview>MarianMisiak_Timeline.png</preview>
		<specimen>MarianMisiak_Timeline_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

    <designer>
		<name>Aoife Mooney</name>
		<country>Ireland</country>
		<email>aoifemooney@gmail.com</email>
		<web>www.mooted.org</web>
		<typeface>Magnimo</typeface>
		<preview>AoifeMooney_Magnimo.png</preview>
		<specimen>AoifeMooney_Magnimo_specimen.pdf</specimen>
		<rop>AoifeMooney_Magnimo_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Octavio Pardo</name>
		<country>Spain</country>
		<email>octaviopardo@gmail.com</email>
		<web>www.oandcompany.es</web>
		<typeface>Cabriole</typeface>
		<preview>OctavioPardo_Cabriole.png</preview>
		<specimen>OctavioPardo_Cabriole_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

    <designer>
		<name>Steve Ross</name>
		<country>Canada</country>
		<email>steve@steveross.ca</email>
		<web>www.steveross.ca</web>
		<typeface>Yukatek</typeface>
		<preview>SteveRoss_Yukatek.png</preview>
		<specimen>SteveRoss_Yukatek_specimen.pdf</specimen>
		<rop>SteveRoss_Yukatek_RoP.pdf</rop>
	</designer>

    <designer>
		<name>Zachary Quinn Scheuren</name>
		<country>USA</country>
		<email>zarijoscha@gmail.com</email>
		<web>www.punchcutter.com</web>
		<typeface>Souriya Chrieng &amp; Luqule</typeface>
		<preview>ZacharyScheuren_SouriyaChriengLuqule.png</preview>
		<specimen>ZacharyScheuren_SouriyaChriengLuqule_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

    <designer>
		<name>Sarah Schumacher</name>
		<country>USA</country>
		<email>info@sarahschumacher.com</email>
		<web>www.sarahschumacher.com</web>
		<typeface>Rhodora &amp; Eskesta</typeface>
		<preview>SarahSchumacher_RhodoraEskesta.png</preview>
		<specimen>SarahSchumacher_RhodoraEskesta_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

    <designer>
		<name>Gunnar Vilhjalmsson</name>
		<country>Iceland</country>
		<email>mail@gunnarvilhjalmsson.net</email>
		<web>gunnarvilhjalmsson.net</web>
		<typeface>Germain</typeface>
		<preview>GunnarVilhjalmsson_Germain.png</preview>
		<specimen>GunnarVilhjalmsson_Germain_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

    <designer>
		<name>Marc Weymann</name>
		<country>Liechtenstein/Switzerland</country>
		<email>info@marcweymann.com</email>
		<web>www.marcweymann.com</web>
		<typeface>Formal</typeface>
		<preview>MarcWeymann_Formal.png</preview>
		<specimen>MarcWeymann_Formal_specimen.pdf</specimen>
		<!-- <rop>MarcWeymann_Formal_RoP.pdf</rop> !! to be update later -->
	</designer>

	<thanks>
	<p>We are all very grateful to a lot of people who helped to make this extraordinary year possible.</p>
	<p>We would like to thank the tutors and staff of the Department of Typography &amp; Graphic Communication, University of Reading, especially Martin Andrews, Gerry Leonidas, James Mosley, Fiona Ross, Michael Twyman, and Gerard Unger.</p>
	<p>We couldn’t have done it without all our families and friends, either!</p>
	</thanks>

</class>

<class year="2009" ready="1">
	<!--<group-specimen>
		<specimen>matd09_group_specimen.pdf</specimen>
		<size>1.4 MB</size>
	</group-specimen> -->

    <designer>
		<name>Amélie Bonet</name>
		<country>France</country>
		<email>hello@ameliebonet.com</email>
		<web>ameliebonet.com</web>
		<typeface>Polydom</typeface>
		<preview>AmelieBonet_Polydom.png</preview>
		<specimen>AmelieBonet_Polydom_specimen.pdf</specimen>
		<!-- do not share RoP -->
	</designer>

 	<designer>
		<name>Camille Boulouis</name>
		<country>France</country>
		<email>camille.boulouis@gmail.com</email>
		<typeface>Guillotine</typeface>
		<preview>CamilleBoulouis_Guillotine.png</preview>
		<specimen>CamilleBoulouis_Guillotine_specimen.pdf</specimen>
		<rop>CamilleBoulouis_Guillotine_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Antonio Cavedoni</name>
		<country>Italy</country>
		<email>antonio@cavedoni.org</email>
		<web>cavedoni.com</web>
		<typeface>Enquire</typeface>
		<preview>AntonioCavedoni_Enquire.png</preview>
		<specimen>AntonioCavedoni_Enquire_specimen.pdf</specimen>
		<rop>AntonioCavedoni_Enquire_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Dave Crossland</name>
		<country>UK</country>
		<email>dave@lab6.com</email>
		<web>abattis.org</web>
		<typeface>Cantarell</typeface>
		<preview>DaveCrossland_Cantarell.png</preview>
		<specimen>DaveCrossland_Cantarell_specimen.pdf</specimen>
		<vendor name="Abattis">abattis.org/cantarell/</vendor>
		<!--<rop>DaveCrossland_Cantarell_RoP.pdf</rop> !! -->
	</designer>

 	<designer>
		<name>Crystian Cruz</name>
		<country>Brazil</country>
		<email>mail@crystiancruz.com</email>
		<web>www.crystiancruz.com</web>
		<typeface>Quartzo</typeface>
		<preview>CrystianCruz_Quartzo.png</preview>
		<specimen>CrystianCruz_Quartzo_specimen.pdf</specimen>
		<rop>CrystianCruz_Quartzo_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Gro Janarv</name>
		<country>Sweden</country>
		<email>gro.janarv@gmail.com</email>
		<web>grojanarv.se</web>
		<typeface>Okapi</typeface>
		<preview>GroJanarv_Okapi.png</preview>
		<specimen>GroJanarv_Okapi_specimen.pdf</specimen>
		<rop>GroJanarv_Okapi_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Lilith Laborey</name>
		<country>France</country>
		<email>lilith@lilithlab.net</email>
		<web>www.lilithlab.net</web>
		<typeface>Capoeira</typeface>
		<preview>LilithLaborey_Capoeira.png</preview>
		<specimen>LilithLaborey_Capoeira_specimen.pdf</specimen>
		<rop>LilithLaborey_Capoeira_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Deema Merdad</name>
		<country>Saudi Arabia</country>
		<email>deema.merdad@gmail.com</email>
		<typeface>Squiggly</typeface>
		<preview>DeemaMerdad_Squiggly.png</preview>
		<specimen>DeemaMerdad_Squiggly_specimen.pdf</specimen>
		<rop>DeemaMerdad_Squiggly_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Julia Petretta (Kaestle)</name>
		<country>Germany</country>
		<email>julia.kaestle@gmail.com</email>
		<web>www.mfgimweb.de</web>
		<typeface>Creon</typeface>
		<preview>JuliaKaestle_Creon.png</preview>
		<specimen>JuliaKaestle_Creon_specimen.pdf</specimen>
		<rop>JuliaKaestle_Creon_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Jonny Pinhorn</name>
		<country>UK</country>
		<email>jon@jonpinhorn.com</email>
		<typeface>Venkat</typeface>
		<preview>JonnyPinhorn_Venkat.png</preview>
		<specimen>JonnyPinhorn_Venkat_specimen.pdf</specimen>
		<rop>JonnyPinhorn_Venkat_RoP.pdf</rop>
	</designer>

  	<designer>
		<name>Émilie Rigaud</name>
		<country>France</country>
		<email>emilie.rigaud@gmail.com</email>
		<web>www.emilie-rigaud.com</web>
		<typeface>Coline</typeface>
		<preview>EmilieRigaud_Coline.png</preview>
		<specimen>EmilieRigaud_Coline_specimen.pdf</specimen>
		<vendor name="A is for Apple">www.aisforapple.eu</vendor>
		<rop>EmilieRigaud_Coline_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Anette Schmidt</name>
		<country>Denmark</country>
		<email>anette@email.com</email>
		<typeface>Anglaise</typeface>
		<preview>AnetteSchmidt_Anglaise.png</preview>
		<specimen>AnetteSchmidt_Anglaise_specimen.pdf</specimen>
		<vendor name="Ladyfingers">new.myfonts.com/fonts/ladyfingers/anglaise/</vendor>
		<rop>AnetteSchmidt_Anglaise_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Eben Sorkin</name>
		<country>US</country>
		<email>eben@eyebytes.com</email>
		<web>eyebytes.com</web>
		<typeface>Arrotino</typeface>
		<preview>EbenSorkin_Arrotino.png</preview>
		<specimen>EbenSorkin_Arrotino_specimen.pdf</specimen>
		<rop>EbenSorkin_Arrotino_RoP.pdf</rop>
	</designer>

 	<designer>
		<name>Claus Eggers Sørensen</name>
		<country>Denmark</country>
		<email>es@forthehearts.net</email>
		<web>www.forthehearts.net</web>
		<typeface>Markant</typeface>
		<preview>ClausEggersSorensen_Markant.png</preview>
		<specimen>ClausEggersSorensen_Markant_specimen.pdf</specimen>
		<webspecimen>www.forthehearts.net</webspecimen>
		<rop>ClausEggersSorensen_Markant_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Gesine Todt</name>
		<country>Germany</country>
		<email>hello@gesine-todt.de</email>
		<web>www.gesine-todt.de</web>
		<typeface>You are here</typeface>
		<preview>GesineTodt_YouAreHere.png</preview>
		<specimen>GesineTodt_YouAreHere_specimen.pdf</specimen>
		<rop>GesineTodt_YouAreHere_RoP.pdf</rop>
	</designer>

    	<thanks>	
    	<p>We’re grateful to a lot of people for helping us all have an extraordinary year.</p>

    	<p>We would all like to thank the tutors and staff of the Department of Typography &amp; Graphic Communication, University of Reading, especially Martin Andrews, Gerry Leonidas, James Mosley, Fiona Ross, Michael Twyman, and Gerard Unger. Cheers to Jo de Baerdemaeker, Erik van Blokland, David Březina, Tobias Frere-Jones, Victor Gaultney, John Hudson, Richard Kegler, Tal Leming, Titus Nemeth, Fred Smeijers, Adam Twardoch, and our dear Type and Media colleagues from KABK.</p>

    	<p>We couldn’t have done it without all our families and friends, either!</p>
    	</thanks>
</class>


<class year="2008" ready="1">
	<group-specimen>
		<specimen>matd08_group_specimen.pdf</specimen>
		<size>1.4 MB</size>
	</group-specimen>

	<designer>
		<name>Andrew Berry</name>
		<country>Australia</country>
		<email>type@andrewberry.com.au</email>
		<web>www.andrewberry.com.au</web>
		<typeface>Hyde</typeface>
		<preview>AndrewBerry_Hyde.png</preview>
		<specimen>AndrewBerry_Hyde_specimen.pdf</specimen>
		<rop>AndrewBerry_Hyde_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Emanuela Conidi</name>
		<country>Italy</country>
		<email>manuconidi@gmail.com</email>
		<typeface>Nabil</typeface>
		<preview>EmanuelaConidi_Nabil.png</preview>
		<specimen>EmanuelaConidi_Nabil_specimen.pdf</specimen>
		<rop>EmanuelaConidi_Nabil_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Melanie Duarte</name>
		<country>USA</country>
		<email>melanieduarte@mac.com</email>
		<typeface>Theodore</typeface>
		<preview>MelanieDuarte_Theodore.png</preview>
		<specimen>MelanieDuarte_Theodore_specimen.pdf</specimen>
		<!-- <rop>MelanieDuarte_Theodore_RoP.pdf</rop> !! -->
	</designer>

	<designer>
		<name>Joke Gossé</name>
		<country>Belgium</country>
		<email>joke.gosse@gmail.com</email>
		<typeface>Melville</typeface>
		<preview>JokeGosse_Melville.png</preview>
		<specimen>JokeGosse_Melville_specimen.pdf</specimen>
		<rop>JokeGosse_Melville_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Michael Hernan</name>
		<country>UK</country>
		<email>michaelhernan@mac.com</email>
		<web>www.fontgroup.com</web>
		<typeface>Pseudo</typeface>
		<preview>MichaelHernan_Pseudo.png</preview>
		<specimen>MichaelHernan_Pseudo_specimen.pdf</specimen>
		<rop>MichaelHernan_Pseudo_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Michael Hochleitner</name>
		<country>Austria</country>
		<email>michi@typejockeys.com</email>
		<web>www.typejockeys.com</web>
		<typeface>Ingeborg</typeface>
		<preview>MichaelHochleitner_Ingeborg.png</preview>
		<specimen>MichaelHochleitner_Ingeborg_specimen.pdf</specimen>
		<vendor name="Typejockeys">www.typejockeys.com/type/6_Ingeborg</vendor>
		<rop>MichaelHochleitner_Ingeborg_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Paul Hunt</name>
		<country>USA</country>
		<web>www.pilcrowtype.com</web>
		<typeface>Grandia &amp; Gandhara</typeface>
		<preview>PaulHunt_GrandiaGandhara.png</preview>
		<specimen>PaulHunt_GrandiaGandhara_specimen.pdf</specimen>
		<rop>PaulHunt_GrandiaGandhara_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Mathieu Réguer</name>
		<country>France</country>
		<email>mathieu.reguer@gmail.com</email>
		<typeface>Cassius &amp; Ali</typeface>
		<preview>MathieuReguer_CassiusAli.png</preview>
		<specimen>MathieuReguer_CassiusAli_specimen.pdf</specimen>
		<rop>MathieuReguer_CassiusAli_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Dan Reynolds</name>
		<country>USA/Germany</country>
		<email>dan@typeoff.de</email>
		<web>www.typeoff.de</web>
		<typeface>Martel/Malabar</typeface>
		<preview>DanReynolds_Martel.png</preview>
		<specimen>DanReynolds_Martel_specimen.pdf</specimen>
		<vendor name="Linotype">http://www.linotype.com/5831/malabar.html</vendor>
		<rop>DanReynolds_Martel_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Yvonne Schüttler</name>
		<country>Germany</country>
		<email>ysch@me.com</email>
		<typeface>Mina</typeface>
		<preview>YvonneSchuettler_Mina.png</preview>
		<specimen>YvonneSchuettler_Mina_specimen.pdf</specimen>
		<!-- <rop>YvonneSchuettler_Mina_RoP.pdf</rop> !! -->
	</designer>

	<designer>
		<name>Emma Williams</name>
		<country>UK</country>
		<email>em.u.williams@gmail.com</email>
		<typeface>Milvus</typeface>
		<preview>EmmaWilliams_Milvus.png</preview>
		<specimen>EmmaWilliams_Milvus_specimen.pdf</specimen>
		<rop>EmmaWilliams_Milvus_RoP.pdf</rop>
	</designer>

	<thanks>	
	<p>We’re grateful to a lot of people for helping us all have an extraordinary year.</p>
	
	<p>Martin Andrews, Jo de Baerdemaeker, Veronika Burian, Rob Banham, Carolyn Davidson, Mary Dyson, Victor Gaultney, Eric Kindel, Gerry Leonidas, Paul Luna, Charlene McGroarty, Hadj Messelles, Tom Milo, Jonathan Hoefler, John Hudson, James Mosley, Linda Reynolds, Daniel Rhatigan, Fiona Ross, José Scaglione, Christian Schwartz, Paul Stiff, Miguel Sousa, Mirjam Somers, Michael Twyman, Gerard Unger, Marjan Unger, Sue Walker, Geoff Wyeth and the entire crew of the Design and Print Unit.</p>
	
	<p>We couldn’t have done it without all our families and friends, either!</p>
	</thanks>
</class>

<class year="2007" ready="1">
	<group-specimen>
		<specimen>matd07_group_specimen.pdf</specimen>
		<size>2.7 MB</size>
	</group-specimen>
		
	<designer>
		<name>Vernon Adams</name>
		<country>UK</country>
		<email>vern@newtypography.co.uk</email>
		<web>www.newtypography.co.uk</web>
		<typeface>Mako</typeface>
		<preview>VernonAdams_Mako.png</preview>
		<specimen>VernonAdams_Mako_specimen.pdf</specimen>
		<!-- <rop>VernonAdams_Mako_RoP.pdf</rop> !! -->
	</designer>

	<designer>
		<name>Jenni Ahonen</name>
		<country>Finland</country>
		<email>ahonen.jenni@gmail.com</email>
		<typeface>Ilona</typeface>
		<preview>JenniAhonen_Ilona.png</preview>
		<specimen>JenniAhonen_Ilona_specimen.pdf</specimen>
		<rop>JenniAhonen_Ilona_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Tim Ahrens</name>
		<country>Germany/UK</country>
		<email>info@justanotherfoundry.com</email>
		<web>justanotherfoundry.com</web>
		<typeface>Herb</typeface>
		<preview>TimAhrens_Herb.png</preview>
		<vendor name="Just Another Foundry">justanotherfoundry.com/herb</vendor>
		<rop>TimAhrens_Herb_RoP.pdf</rop>
	</designer>

	<designer>
		<name>David Březina</name>
		<country>Czechia</country>
		<email>brezina@davi.cz</email>
		<web>davi.cz</web>
		<typeface>Skolar &amp; Surat</typeface>
		<preview>DavidBrezina_SkolarSurat.png</preview>
		<specimen>DavidBrezina_SkolarSurat_specimen.pdf</specimen>
		<vendor name="TypeTogether">www.type-together.com/Skolar</vendor>
		<rop>DavidBrezina_SkolarSurat_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Valentin Brustaux</name>
		<country>Switzerland</country>
		<web>regular.li</web>
		<typeface>Tiina</typeface>
		<preview>ValentinBrustaux_Tiina.png</preview>
		<vendor name="OurType">ourtype.com</vendor>
		
		<!-- do not share RoP -->
	</designer>

	<designer>
		<name>Gerben Dollen</name>
		<country>Netherlands</country>
		<email>info@typemafia.com</email>
		<web>www.typemafia.com</web>
		<typeface>Actium</typeface>
		<preview>GerbenDollen_Actium.png</preview>
		<specimen>GerbenDollen_Actium_specimen.pdf</specimen>
		<vendor name="Type Mafia">new.myfonts.com/fonts/typemafia/actium/</vendor>
		<rop>GerbenDollen_Actium_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Nicole Dotin</name>
		<country>USA</country>
		<email>nicole@processtypefoundry.com</email>
		<web>www.processtypefoundry.com</web>
		<typeface>Elena</typeface>
		<preview>NicoleDotin_Elena.png</preview>
		<specimen>NicoleDotin_Elena_specimen.pdf</specimen>
		<rop>NicoleDotin_Elena_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Christina Economidou</name>
		<country>Cyprus/UK</country>
		<email>christina_economidou_8@hotmail.com</email>
		<typeface>Phoebe</typeface>
		<preview>ChristinaEconomidou_Phoebe.png</preview>
		<specimen>ChristinaEconomidou_Phoebe_specimen.pdf</specimen>
		<rop>ChristinaEconomidou_Phoebe_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Rob Keller</name>
		<country>USA</country>
		<email>rob@youshouldliketypetoo.com</email>
		<web>motaitalic.com</web>
		<typeface>Vesper</typeface>
		<preview>RobKeller_Vesper.png</preview>
		<vendor name="Mota Italic">www.motaitalic.com/fonts/vesper</vendor>
		<!-- do not share RoP -->
	</designer>
	
	<designer>
		<name>Nicolien van der Keur</name>
		<country>Netherlands</country>
		<email>type@vanderkeur.net</email>
		<web>www.vanderkeur.net</web>
		<typeface>Sirba</typeface>
		<preview>NicolienvanderKeur_Sirba.png</preview>
		<specimen>NicolienvanderKeur_Sirba_specimen.pdf</specimen>
		<vendor name="Type Together">type-together.com/Sirba</vendor>
		<rop>NicolienvanderKeur_Sirba_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Ian Moore</name>
		<country>UK</country>
		<email>made@byfrank.co.uk</email>
		<web>www.madebyfrank.co.uk</web>
		<typeface>Broomfield</typeface>
		<preview>IanMoore_Broomfield.png</preview>
		<webspecimen>www.madebyfrank.co.uk/tdbooklet.html</webspecimen>
		<rop>IanMoore_Broomfield_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Daniel Rhatigan</name>
		<country>USA</country>
		<email>sparky@ultrasparky.org</email>
		<web>www.ultrasparky.org</web>
		<typeface>Gina</typeface>
		<preview>DanielRhatigan_Gina.png</preview>
		<specimen>DanielRhatigan_Gina_specimen.pdf</specimen>
		<rop>DanielRhatigan_Gina_RoP.pdf</rop>
	</designer>

	<designer>
		<name>Alice Savoie</name>
		<country>France</country>
		<email>alice@frenchtype.com</email>
		<web>www.frenchtype.com</web>
		<typeface>Capucine</typeface>
		<preview>AliceSavoie_Capucine.png</preview>
		<specimen>AliceSavoie_Capucine_specimen.pdf</specimen>
		<vendor name="Process Type Foundry">processtypefoundry.com/fonts/capucine/</vendor>
		<rop>AliceSavoie_Capucine_RoP.pdf</rop>
	</designer>
	
	<designer>
		<name>Fernando de Mello Vargas</name>
		<country>Brazil</country>
		<email>fermello@fermello.org</email>
		<web>www.fermello.org</web>
		<typeface>Frida</typeface>
		<preview>FernandoMello_Frida.png</preview>
		<specimen>FernandoMello_Frida_specimen.pdf</specimen>
		<rop>FernandoMello_Frida_RoP.pdf</rop>
	</designer>
	
	<thanks>	
	<p>We’re grateful to a lot of people for helping us all have an extraordinary year.</p>

	<p>Martin Andrews, Jo de Baerdemaeker,
	Rob Banham, Peter Biľak, David Bolton,
	Ron Carpenter, Carolyn Davidson, Bram
	de Does, Mary Dyson, Phil Garnham,
	Victor Gaultney, Nadja Guggi, Eric Kindel,
	Gerry Leonidas, Paul Luna, Charlene